batch_size: 1
data_path: D:/data/modelnet40_ply_hdf5_2048/train_files.txt
lrf_nn: 30
k: 9
rand_sample: 16
max_epoch: 100
first_transform_units: 64, 64
second_transform_units: 64, 64
nclasses: 40
immediate_nchannels: 16
min_margin: 0.2
max_margin: 0.9